# Setup
title: "Leon's Blog(n)"
tagline: "v.1.9.8.4"
url: "/blog/" 
paginate: 10
baseurl: "/blog/"
permalink: :title
description: "Part time Fencer, Kpop and Swing Dancer, Alto Sax and Piano Player, Animator, Mathematician, Football Player, Fencer, 풀타임 멍청이"
host: "localhost"
port: 4000
# host: "10.32.226.35"

# destination: /var/www/html

kramdown:
  parse_span_html: false

sanitize: true

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Leon Yao

# Custom vars
version: 3.0.0

defaults:
  - scope:
      # path: "assets/img"
      path: "tangle_families"

    values:
      images: true
    

# theme: jekyll-theme-hyde
